#!/bin/bash

##################################################################################################
# 
# DEPENDENCY: install goodtables before running: https://github.com/frictionlessdata/goodtables-py
# 
# NOTE: 'MISSING HEADER' ERRORS WILL BE GENERATED for all TSVs with no records in them (i.e. TSVs
# containing only header lines). If the tables associated with the offending TSVs are supposed to
# be empty, then these errors can and should be ignored; the table format is valid despite
# goodtables' complaints.
# 
# Arthur Brady (Univ. of MD Inst. for Genome Sciences) wrote this script to validate
# HMP ETL data against the C2M2 Level 0 JSON Schema specification prior to submission to CFDE
# for ingestion into the central C2M2 database.
# 
# Creation date: 2020-05
# Lastmod date unless I forgot to change it: 2020-05-27
#
# contact email: abrady@som.umaryland.edu
# 
##################################################################################################

instanceDir=002_HMP__C2M2_Level_0_preload__preBag_output_files

schemaFile=C2M2_Level_0.datapackage.json

headerFile=data_validation_report.header

outFile=data_validation_report.HMP.Level_0.txt

tempFile=data_validation_report.temp

echo -e "##################################################################################################
# 
# NOTE: ALL ERRORS MARKED \"[missing-header]\" CAN BE IGNORED
# 
# They're generated by empty tables, which are allowed by the C2M2 spec. I can't find a way to
# get goodtables to be cool with a TSV containing just a header line and no records, so it
# keeps throwing these.
# 
# Any _other_ errors should be handled.
# 
##################################################################################################
" > $headerFile

goodtables validate -o $outFile $instanceDir/$schemaFile

cat $headerFile $outFile > $tempFile

mv $tempFile $outFile

rm $headerFile


